### ISSUE TITLE
Mekanism updated which now breaks - Lasers, Weapons and Turrets mods.

### ISSUE THREAD

**Issue by SirTwsted** [x3rdev/MekanismTurrets#10]
As the title says:
Mekanism updated which now breaks - Lasers, Weapons and Turrets mods.

I am using MC v1.21 with NEOForge v21.0.114,  also tried it with v21.0.113

![Mekanism ERROR after update](https://github.com/user-attachments/assets/64f58484-0b74-48e7-8cb1-083670d4be6f)

![Screenshot_313](https://github.com/user-attachments/assets/bbf6c957-e39f-4706-8da4-7b3a911bdaa7)

end transmission:

**Comment by x3rdev** [comment]
Error on my side that appears on both 1.20.1 and 1.21, will be fixed soon.

**Comment by x3rdev** [comment]
Ok, fixed in newest update. Im not sure why the game was letting you launch with a newer version of mekanism but whatever, I guess this error came up first. Check curseforge soon for an updated file, or grab it from the actions tab

**Comment by SirTwsted** [comment]
Hi @x3rdev 
Nope, not fixed yet. 
Just came home from work, seen your post and updated Turrets mod and got this in return.

![Screenshot_316](https://github.com/user-attachments/assets/6221cda5-f30a-4386-bcad-6cca27bd9db4)

![Screenshot_317](https://github.com/user-attachments/assets/32a1ac2f-7f25-4a57-95da-c4197a8c05ef)


🤷‍♀️😳

**Comment by x3rdev** [comment]
Hi, this issue isn't fixed yet on curseforge as I want to push a larger array of fixes, the file will be available on curseforge soon.

**Comment by SirTwsted** [comment]
aah ok, understood.  Thank you.   🥰
